export enum EVENT_CATEGORY {
  HEALTH_SCREENING = 1,
  MENTAL_WELLNESS = 2,
  FITNESS_EXERCISE = 3,
  DIET_NUTRITION = 4,
  WORK_LIFE_BALANCE = 5,
  HEALTH_TALK_EDUCATION = 6,
}

export const EVENT_CATEGORY_LABELS: Record<EVENT_CATEGORY, string> = {
  [EVENT_CATEGORY.HEALTH_SCREENING]: "Health Screening",
  [EVENT_CATEGORY.MENTAL_WELLNESS]: "Mental Wellness",
  [EVENT_CATEGORY.FITNESS_EXERCISE]: "Fitness & Exercise",
  [EVENT_CATEGORY.DIET_NUTRITION]: "Diet & Nutrition",
  [EVENT_CATEGORY.WORK_LIFE_BALANCE]: "Work-Life Balance",
  [EVENT_CATEGORY.HEALTH_TALK_EDUCATION]: "Health Talk & Education",
};
